# application-docker.yml
spring:
  output:
    ansi:
      enabled: always
  config:
    import: "optional:configserver:http://config-service:8088"
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: beans,env,health,info,metrics,mappings,prometheus
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

tracing:
  url: http://jaeger:4318/v1/traces





