version: "3.9"

services:
  config-service:
    container_name: config-service.latest
    image: jasbir008/config-service:latest
    ports:
      - "8088:8088"
    networks:
      - ecommerce-app
    restart: on-failure

  discovery-service:
    container_name: discovery-service.latest
    image: jasbir008/discovery-service:latest
    ports:
      - "8061:8061"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: curl --fail http://localhost:8061/actuator/health || exit 1
    networks:
      - ecommerce-app
    restart: on-failure

  gateway-service:
    container_name: gateway-service.latest
    image: jasbir008/gateway-service:latest
    ports:
      - "8060:8060"
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ecommerce-app
    restart: on-failure

  product-service:
    container_name: product-service.latest
    image: jasbir008/product-service:latest
    ports:
      - "8191:8191"
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ecommerce-app
    restart: on-failure

networks:
  ecommerce-app:
    driver: bridge