#version: "3.9"
services:
  config-service:
    container_name: config-service.latest
    image: jasbir008/config-service:latest
    ports:
      - "8088:8088"
  discovery-service:
    container_name: discovery-service.latest
    image: jasbir008/discovery-service:latest
    ports:
      - "8061:8061"
    healthcheck:
      test: curl --fail http://localhost:8061/eureka/v2/apps || exit 1
    environment:
      SPRING_PROFILES_ACTIVE: docker
  gateway-service:
    container_name: gateway-service.latest
    image: jasbir008/gateway-service:latest
    ports:
      - "8060:8060"
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - config-service
      - discovery-service

networks:
  ecommerce-network:
    name: ecommerce-app