version: "3.9"

services:
  config-service:
    container_name: config-service.latest
    image: jasbir008/config-service:latest
    ports:
      - "8088:8088"
    healthcheck:
      test: curl --fail http://localhost:8088/discovery/docker  || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
    restart: on-failure

  discovery-service:
    container_name: discovery-service.latest
    image: jasbir008/discovery-service:latest
    ports:
      - "8061:8061"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    healthcheck:
      test: curl --fail http://localhost:8061/eureka/v2/apps || exit 1
      interval: 4s
      timeout: 2s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: docker

  gateway-service:
    container_name: gateway-service.latest
    image: jasbir008/gateway-service:latest
    ports:
      - "8060:8060"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_started
    links:
      - config-service
      - discovery-service
    restart: on-failure

  product-service:
    container_name: product-service.latest
    image: jasbir008/product-service:latest
    ports:
      - "8191:8191"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_started
    restart: on-failure
