server:
    port: 8061
spring:
  application:
    name: discovery-service
  config:
    import: "optional:configserver:http://localhost:8088"
  output:
    ansi:
      enabled: always

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: beans,env,health,info,metrics,mappings,prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans